package com.example.localization

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    HINDI("hi", "Hindi", "हिन्दी"),
    MARATHI("mr", "Marathi", "मराठी"),
    SANSKRIT("sa", "Sanskrit", "संस्कृतम्"),
    BENGALI("bn", "Bengali", "বাংলা"),
    GUJARATI("gu", "Gujarati", "ગુજરાતી"),
    TAMIL("ta", "Tamil", "தமிழ்"),
    TELUGU("te", "Telugu", "తెలుగు"),
    KANNADA("kn", "Kannada", "ಕನ್ನಡ"),
    PUNJABI("pa", "Punjabi", "ਪੰਜਾਬੀ"),
    URDU("ur", "Urdu", "اردو")
}

data class StringsDefinition(
    val appName: String,
    val tagline: String,
    val roleParent: String,
    val roleDriver: String,
    val roleAdmin: String,
    val busOnTheWay: String,
    val busAtSchool: String,
    val busCompleted: String,
    val eta: String,
    val nextStop: String,
    val tripStarted: String,
    val childPickedUp: String,
    val travelling: String,
    val schoolArrival: String,
    val homeDropOff: String,
    val connectBus: String,
    val enterBusCode: String,
    val startTrip: String,
    val endTrip: String,
    val emergencyAlert: String,
    val liveGpsMode: String,
    val simGpsActive: String,
    val realGpsActive: String,
    val searchPlaceholder: String,
    val notifications: String,
    val auditLogs: String,
    val safetyCenter: String,
    val noBusConnected: String
)

object LocalizationManager {
    private val translations = mapOf(
        AppLanguage.ENGLISH to StringsDefinition(
            appName = "SafeRide",
            tagline = "Your child’s journey. Your peace of mind.",
            roleParent = "Parent / Guardian",
            roleDriver = "Driver / Bus Owner",
            roleAdmin = "Super Admin Control Center",
            busOnTheWay = "BUS IS ON THE WAY",
            busAtSchool = "ARRIVED AT SCHOOL",
            busCompleted = "TRIP COMPLETED",
            eta = "ETA",
            nextStop = "Next stop",
            tripStarted = "Trip started",
            childPickedUp = "Child picked up",
            travelling = "Travelling",
            schoolArrival = "School arrival",
            homeDropOff = "Home drop-off",
            connectBus = "Connect to a Bus",
            enterBusCode = "Enter Bus Code (e.g. SR-7K42Q)",
            startTrip = "START TRIP",
            endTrip = "END TRIP",
            emergencyAlert = "EMERGENCY ALERT",
            liveGpsMode = "LIVE GPS RADAR",
            simGpsActive = "SIMULATED GPS ACTIVE",
            realGpsActive = "LIVE GPS ACTIVE",
            searchPlaceholder = "Search authorized records...",
            notifications = "Notifications",
            auditLogs = "Audit Logs",
            safetyCenter = "Safety Center",
            noBusConnected = "No bus connected yet."
        ),
        AppLanguage.HINDI to StringsDefinition(
            appName = "SafeRide",
            tagline = "आपके बच्चे की यात्रा। आपका सुकून।",
            roleParent = "अभिभावक / माता-पिता",
            roleDriver = "चालक / बस स्वामी",
            roleAdmin = "सुपर एडमिन नियंत्रण केंद्र",
            busOnTheWay = "आपकी बस रास्ते में है",
            busAtSchool = "स्कूल पहुंच चुकी है",
            busCompleted = "यात्रा पूर्ण हुई",
            eta = "अनुमानित समय",
            nextStop = "अगला स्टॉप",
            tripStarted = "यात्रा प्रारंभ",
            childPickedUp = "बच्चे को पिक किया गया",
            travelling = "यात्रा जारी है",
            schoolArrival = "स्कूल आगमन",
            homeDropOff = "घर ड्रॉप किया गया",
            connectBus = "बस से जुड़ें",
            enterBusCode = "बस कोड दर्ज करें (उदा. SR-7K42Q)",
            startTrip = "यात्रा प्रारंभ करें",
            endTrip = "यात्रा समाप्त करें",
            emergencyAlert = "आपातकालीन चेतावनी",
            liveGpsMode = "लाइव जीपीएस रडार",
            simGpsActive = "सिमुलेटेड जीपीएस सक्रिय",
            realGpsActive = "लाइव जीपीएस सक्रिय",
            searchPlaceholder = "रिकॉर्ड खोजें...",
            notifications = "सूचनाएं",
            auditLogs = "ऑडिट लॉग",
            safetyCenter = "सुरक्षा केंद्र",
            noBusConnected = "अभी तक कोई बस कनेक्ट नहीं है।"
        ),
        AppLanguage.MARATHI to StringsDefinition(
            appName = "SafeRide",
            tagline = "तुमच्या पाल्याचा प्रवास. तुमचे मनःस्वास्थ्य.",
            roleParent = "पालक / संरक्षक",
            roleDriver = "चालक / बस मालक",
            roleAdmin = "सुपर ॲडमिन नियंत्रण केंद्र",
            busOnTheWay = "तुमची बस मार्गावर आहे",
            busAtSchool = "शाळेत पोहोचली",
            busCompleted = "प्रवास पूर्ण झाला",
            eta = "अंदाजे वेळ",
            nextStop = "पुढचा थांबा",
            tripStarted = "प्रवास सुरू",
            childPickedUp = "विद्यार्थी बसमध्ये बसला",
            travelling = "प्रवास सुरू आहे",
            schoolArrival = "शाळेत आगमन",
            homeDropOff = "घरी सोडले",
            connectBus = "बस कनेक्ट करा",
            enterBusCode = "बस कोड प्रविष्ट करा (उदा. SR-7K42Q)",
            startTrip = "प्रवास सुरू करा",
            endTrip = "प्रवास संपवा",
            emergencyAlert = "तातडीची सूचना",
            liveGpsMode = "लाइव्ह जीपीएस रडार",
            simGpsActive = "सिम्युलेटेड जीपीएस चालू",
            realGpsActive = "लाइव्ह जीपीएस चालू",
            searchPlaceholder = "नोंदी शोधा...",
            notifications = "सूचना",
            auditLogs = "ऑडिट लॉग",
            safetyCenter = "सुरक्षा केंद्र",
            noBusConnected = "अद्याप कोणतीही बस जोडलेली नाही."
        ),
        AppLanguage.SANSKRIT to StringsDefinition(
            appName = "SafeRide",
            tagline = "भवतः शिशोः यात्रा। भवतः मनःशान्तिः।",
            roleParent = "अभिभावकः",
            roleDriver = "चालकः / स्वामी",
            roleAdmin = "प्रमुख प्रशासक केन्द्रम्",
            busOnTheWay = "यानं मार्गे अस्ति",
            busAtSchool = "विद्यालये सम्प्राप्तम्",
            busCompleted = "यात्रा समाप्ता",
            eta = "अनुमानित समयः",
            nextStop = "अग्रिम विरामस्थानम्",
            tripStarted = "यात्रा आरब्धा",
            childPickedUp = "शिशुः यानं प्रविष्टः",
            travelling = "यात्रा प्रचलति",
            schoolArrival = "विद्यालय आगमनम्",
            homeDropOff = "गृह सम्प्राप्तिः",
            connectBus = "यानं संयोजयतु",
            enterBusCode = "यान कूटसंख्या प्रविशतु",
            startTrip = "यात्रा प्रारभताम्",
            endTrip = "यात्रा समाप्यताम्",
            emergencyAlert = "आपत्कालीन सूचना",
            liveGpsMode = "प्रत्यक्ष जीपीएस रडार",
            simGpsActive = "कल्पित जीपीएस सक्रियम्",
            realGpsActive = "प्रत्यक्ष जीपीएस सक्रियम्",
            searchPlaceholder = "अन्वेषणं कुर्वन्तु...",
            notifications = "वार्ताः",
            auditLogs = "लेखापत्राणि",
            safetyCenter = "सुरक्षा केन्द्रम्",
            noBusConnected = "अद्यापि यानं न संयोजितम्।"
        ),
        AppLanguage.BENGALI to StringsDefinition(
            appName = "SafeRide",
            tagline = "আপনার সন্তানের যাত্রা। আপনার মনের শান্তি।",
            roleParent = "অভিভাবক",
            roleDriver = "চালক / বাস মালিক",
            roleAdmin = "সুপার অ্যাডমিন নিয়ন্ত্রণ কেন্দ্র",
            busOnTheWay = "বাস রাস্তায় রয়েছে",
            busAtSchool = "স্কুলে পৌঁছেছে",
            busCompleted = "যাত্রা সম্পন্ন হয়েছে",
            eta = "আনুমানিক সময়",
            nextStop = "পরবর্তী স্টপ",
            tripStarted = "যাত্রা শুরু",
            childPickedUp = "সন্তান বাসে উঠেছে",
            travelling = "যাত্রা চলছে",
            schoolArrival = "স্কুলে আগমন",
            homeDropOff = "বাড়ি পৌঁছে দেওয়া হয়েছে",
            connectBus = "বাসের সাথে যুক্ত হন",
            enterBusCode = "বাস কোড লিখুন (যেমন SR-7K42Q)",
            startTrip = "যাত্রা শুরু করুন",
            endTrip = "যাত্রা শেষ করুন",
            emergencyAlert = "জরুরি সতর্কতা",
            liveGpsMode = "লাইভ জিপিএস রাডার",
            simGpsActive = "সিমুলেটেড জিপিএস সক্রিয়",
            realGpsActive = "লাইভ জিপিএস সক্রিয়",
            searchPlaceholder = "অনুসন্ধান করুন...",
            notifications = "বিজ্ঞপ্তি",
            auditLogs = "অডিট লগ",
            safetyCenter = "নিরাপত্তা কেন্দ্র",
            noBusConnected = "এখনও কোনো বাস সংযুক্ত নেই।"
        ),
        AppLanguage.GUJARATI to StringsDefinition(
            appName = "SafeRide",
            tagline = "તમારા બાળકની મુસાફરી. તમારી માનસિક શાંતિ.",
            roleParent = "વાલી / માતાપિતા",
            roleDriver = "ડ્રાઈવર / બસ માલિક",
            roleAdmin = "સુપર એડમિન નિયંત્રણ કેન્દ્ર",
            busOnTheWay = "બસ રસ્તા પર છે",
            busAtSchool = "શાળાએ પહોંચી ગયા",
            busCompleted = "મુસાફરી પૂર્ણ થઈ",
            eta = "અંદાજિત સમય",
            nextStop = "આગળનું સ્ટોપ",
            tripStarted = "મુસાફરી શરૂ થઈ",
            childPickedUp = "બાળક પિક થયું",
            travelling = "મુસાફરી ચાલુ છે",
            schoolArrival = "શાળા આગમન",
            homeDropOff = "ઘરે પહોંચ્યા",
            connectBus = "બસ સાથે જોડાઓ",
            enterBusCode = "બસ કોડ દાખલ કરો (દા.ત. SR-7K42Q)",
            startTrip = "મુસાફરી શરૂ કરો",
            endTrip = "મુસાફરી સમાપ્ત કરો",
            emergencyAlert = "કટોકટી ચેતવણી",
            liveGpsMode = "લાઇવ જીપીએસ રડાર",
            simGpsActive = "સિમ્યુલેટેડ જીપીએસ સક્રિય",
            realGpsActive = "લાઇવ જીપીએસ સક્રિય",
            searchPlaceholder = "શોધો...",
            notifications = "સૂચનાઓ",
            auditLogs = "ઓડિટ લોગ",
            safetyCenter = "સુરક્ષા કેન્દ્ર",
            noBusConnected = "હજુ સુધી કોઈ બસ જોડાયેલ નથી."
        ),
        AppLanguage.TAMIL to StringsDefinition(
            appName = "SafeRide",
            tagline = "உங்கள் குழந்தையின் பயணம். உங்கள் மன அமைதி.",
            roleParent = "பெற்றோர் / பாதுகாவலர்",
            roleDriver = "ஓட்டுநர் / பேருந்து உரிமையாளர்",
            roleAdmin = "சூப்பர் அட்மின் கட்டுப்பாட்டு மையம்",
            busOnTheWay = "பேருந்து வழியில் உள்ளது",
            busAtSchool = "பள்ளியை அடைந்தது",
            busCompleted = "பயணம் முடிந்தது",
            eta = "மதிப்பிடப்பட்ட நேரம்",
            nextStop = "அடுத்த நிறுத்தம்",
            tripStarted = "பயணம் தொடங்கியது",
            childPickedUp = "குழந்தை ஏறினார்",
            travelling = "பயணத்தில் உள்ளது",
            schoolArrival = "பள்ளி வருகை",
            homeDropOff = "வீட்டில் இறக்கப்பட்டது",
            connectBus = "பேருந்துடன் இணையுங்கள்",
            enterBusCode = "பேருந்து குறியீட்டை உள்ளிடவும்",
            startTrip = "பயணத்தை தொடங்கு",
            endTrip = "பயணத்தை முடி",
            emergencyAlert = "அவசர எச்சரிக்கை",
            liveGpsMode = "நேரலை ஜிபிஎஸ் ரேடார்",
            simGpsActive = "மாதிரி ஜிபிஎஸ் செயலில் உள்ளது",
            realGpsActive = "நேரலை ஜிபிஎஸ் செயலில் உள்ளது",
            searchPlaceholder = "தேடுங்கள்...",
            notifications = "அறிவிப்புகள்",
            auditLogs = "தணிக்கை பதிவு",
            safetyCenter = "பாதுகாப்பு மையம்",
            noBusConnected = "பேருந்து இன்னும் இணைக்கப்படவில்லை."
        ),
        AppLanguage.TELUGU to StringsDefinition(
            appName = "SafeRide",
            tagline = "మీ పిల్లల ప్రయాణం. మీ మనశ్శాంతి.",
            roleParent = "తల్లిదండ్రులు / సంరక్షకులు",
            roleDriver = "డ్రైవర్ / బస్సు యజమాని",
            roleAdmin = "సూపర్ అడ్మిన్ కంట్రోల్ సెంటర్",
            busOnTheWay = "బస్సు మార్గంలో ఉంది",
            busAtSchool = "పాఠశాలకు చేరుకుంది",
            busCompleted = "ప్రయాణం పూర్తయింది",
            eta = "అంచనా సమయం",
            nextStop = "తదుపరి స్టాప్",
            tripStarted = "ప్రయాణం ప్రారంభమైంది",
            childPickedUp = "పిల్లవాడు ఎక్కాడు",
            travelling = "ప్రయాణం సాగుతోంది",
            schoolArrival = "పాఠశాల రాక",
            homeDropOff = "ఇంటి వద్ద దింపారు",
            connectBus = "బస్సుతో కనెక్ట్ అవ్వండి",
            enterBusCode = "బస్సు కోడ్ నమోదు చేయండి",
            startTrip = "ప్రయాణం ప్రారంభించండి",
            endTrip = "ప్రయాణం ముగించండి",
            emergencyAlert = "అత్యవసర హెచ్చరిక",
            liveGpsMode = "లైవ్ జీపీఎస్ రాడార్",
            simGpsActive = "సిమ్యులేటెడ్ జీపీఎస్ యాక్టివ్",
            realGpsActive = "లైవ్ జీపీఎస్ యాక్టివ్",
            searchPlaceholder = "వెతకండి...",
            notifications = "నోటిఫికేషన్లు",
            auditLogs = "ఆడిట్ లాగ్స్",
            safetyCenter = "రక్షణ కేంద్రం",
            noBusConnected = "ఇంకా బస్సు కనెక్ట్ చేయబడలేదు."
        ),
        AppLanguage.KANNADA to StringsDefinition(
            appName = "SafeRide",
            tagline = "ನಿಮ್ಮ ಮಗುವಿನ ಪ್ರಯಾಣ. ನಿಮ್ಮ ಮನಸ್ಸಿನ ಶಾಂತಿ.",
            roleParent = "ಪೋಷಕರು / ರಕ್ಷಕರು",
            roleDriver = "ಚಾಲಕ / ಬಸ್ ಮಾಲೀಕ",
            roleAdmin = "ಸೂಪರ್ ಅಡ್ಮಿನ್ ನಿಯಂತ್ರಣ ಕೇಂದ್ರ",
            busOnTheWay = "ಬಸ್ಸು ಮಾರ್ಗದಲ್ಲಿದೆ",
            busAtSchool = "ಶಾಲೆಗೆ ತಲುಪಿದೆ",
            busCompleted = "ಪ್ರಯಾಣ ಪೂರ್ಣಗೊಂಡಿದೆ",
            eta = "ಅಂದಾಜು ಸಮಯ",
            nextStop = "ಮುಂದಿನ ನಿಲ್ದಾಣ",
            tripStarted = "ಪ್ರಯಾಣ ಪ್ರಾರಂಭವಾಯಿತು",
            childPickedUp = "ಮಗು ಹತ್ತಿಕೊಂಡಿದೆ",
            travelling = "ಪ್ರಯಾಣ ಮುಂದುವರೆದಿದೆ",
            schoolArrival = "ಶಾಲೆಗೆ ಆಗಮನ",
            homeDropOff = "ಮನೆಗೆ ಇಳಿಸಲಾಯಿತು",
            connectBus = "ಬಸ್‌ಗೆ ಸಂಪರ್ಕಪಡಿಸಿ",
            enterBusCode = "ಬಸ್ ಕೋಡ್ ನಮೂದಿಸಿ",
            startTrip = "ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಿ",
            endTrip = "ಪ್ರಯಾಣ ಮುಗಿಸಿ",
            emergencyAlert = "ತುರ್ತು ಎಚ್ಚರಿಕೆ",
            liveGpsMode = "ಲೈವ್ ಜಿಪಿಎಸ್ ರೇಡಾರ್",
            simGpsActive = "ಸಿಮ್ಯುಲೇಟೆಡ್ ಜಿಪಿಎಸ್ ಸಕ್ರಿಯ",
            realGpsActive = "ಲೈವ್ ಜಿಪಿಎಸ್ ಸಕ್ರಿಯ",
            searchPlaceholder = "ಹುಡುಕಿ...",
            notifications = "ಅಧಿಸೂಚನೆಗಳು",
            auditLogs = "ಆಡಿಟ್ ಲಾಗ್‌ಗಳು",
            safetyCenter = "ಸುರಕ್ಷತಾ ಕೇಂದ್ರ",
            noBusConnected = "ಇನ್ನೂ ಯಾವುದೇ ಬಸ್ ಸಂಪರ್ಕಗೊಂಡಿಲ್ಲ."
        ),
        AppLanguage.PUNJABI to StringsDefinition(
            appName = "SafeRide",
            tagline = "ਤੁਹਾਡੇ ਬੱਚੇ ਦਾ ਸਫ਼ਰ। ਤੁਹਾਡਾ ਸਕੂਨ।",
            roleParent = "ਮਾਪੇ / ਸਰਪ੍ਰਸਤ",
            roleDriver = "ਡਰਾਈਵਰ / ਬੱਸ ਮਾਲਕ",
            roleAdmin = "ਸੁਪਰ ਐਡਮਿਨ ਕੰਟਰੋਲ ਸੈਂਟਰ",
            busOnTheWay = "ਬੱਸ ਰਸਤੇ ਵਿੱਚ ਹੈ",
            busAtSchool = "ਸਕੂਲ ਪਹੁੰਚ ਗਈ",
            busCompleted = "ਸਫ਼ਰ ਪੂਰਾ ਹੋਇਆ",
            eta = "ਅੰਦਾਜ਼ਨ ਸਮਾਂ",
            nextStop = "ਅਗਲਾ ਸਟਾਪ",
            tripStarted = "ਸਫ਼ਰ ਸ਼ੁਰੂ",
            childPickedUp = "ਬੱਚੇ ਨੂੰ ਪਿਕ ਕੀਤਾ ਗਿਆ",
            travelling = "ਸਫ਼ਰ ਜਾਰੀ ਹੈ",
            schoolArrival = "ਸਕੂਲ ਆਗਮਨ",
            homeDropOff = "ਘਰ ਉਤਾਰ ਦਿੱਤਾ ਗਿਆ",
            connectBus = "ਬੱਸ ਨਾਲ ਜੁੜੋ",
            enterBusCode = "ਬੱਸ ਕੋਡ ਦਾਖਲ ਕਰੋ",
            startTrip = "ਸਫ਼ਰ ਸ਼ੁਰੂ ਕਰੋ",
            endTrip = "ਸਫ਼ਰ ਖ਼ਤਮ ਕਰੋ",
            emergencyAlert = "ਸੰਕਟਕਾਲੀਨ ਚੇਤਾਵਨੀ",
            liveGpsMode = "ਲਾਈਵ ਜੀਪੀਐਸ ਰਾਡਾਰ",
            simGpsActive = "ਸਿਮੂਲੇਟਿਡ ਜੀਪੀਐਸ ਸਰਗਰਮ",
            realGpsActive = "ਲਾਈਵ ਜੀਪੀਐਸ ਸਰਗਰਮ",
            searchPlaceholder = "ਖੋਜੋ...",
            notifications = "ਸੂਚਨਾਵਾਂ",
            auditLogs = "ਆਡਿਟ ਲੌਗ",
            safetyCenter = "ਸੁਰੱਖਿਆ ਕੇਂਦਰ",
            noBusConnected = "ਅਜੇ ਤੱਕ ਕੋਈ ਬੱਸ ਜੁੜੀ ਨਹੀਂ।"
        ),
        AppLanguage.URDU to StringsDefinition(
            appName = "SafeRide",
            tagline = "آپ کے بچے کا سفر۔ آپ کا اطمینان۔",
            roleParent = "والدین / سرپرست",
            roleDriver = "ڈرائیور / بس کا مالک",
            roleAdmin = "سپر ایڈمن کنٹرول سینٹر",
            busOnTheWay = "بس راستے میں ہے",
            busAtSchool = "اسکول پہنچ گئی",
            busCompleted = "سفر مکمل ہو گیا",
            eta = "متوقع وقت",
            nextStop = "اگلا اسٹاپ",
            tripStarted = "سفر شروع ہوا",
            childPickedUp = "بچہ سوار ہو گیا",
            travelling = "سفر جاری ہے",
            schoolArrival = "اسکول آمد",
            homeDropOff = "گھر پر چھوڑ دیا گیا",
            connectBus = "بس سے منسلک ہوں",
            enterBusCode = "بس کوڈ درج کریں",
            startTrip = "سفر شروع کریں",
            endTrip = "سفر ختم کریں",
            emergencyAlert = "ہنگامی الرٹ",
            liveGpsMode = "لائیو جی پی ایس ریڈار",
            simGpsActive = "سمولیٹڈ جی پی ایس فعال",
            realGpsActive = "لائیو جی پی ایس فعال",
            searchPlaceholder = "تلاش کریں...",
            notifications = "اطلاعات",
            auditLogs = "آڈٹ لاگس",
            safetyCenter = "سیفٹی سینٹر",
            noBusConnected = "ابھی تک کوئی بس منسلک نہیں ہے۔"
        )
    )

    fun getStrings(language: AppLanguage): StringsDefinition {
        return translations[language] ?: translations[AppLanguage.ENGLISH]!!
    }
}
